### PR TITLE
Add github actions build

### PR DESCRIPTION
**Pull request by chris-doehring**
This PR adds the GitHub actions build as hook to any git push, in order to have a green build whenever merging a pull request.

### CODE REVIEW

**Comment by chris-doehring** [comment]
Proof of running build: https://github.com/chris-doehring/rundeck-api-client/actions/runs/417704644

**Comment by ftw-soft** [comment]
Hi @chris-doehring 
Thanks for the PR.
But Github actions are useless for this repository I think.
The only reason to create them here - automate testing.
But current repo does not have any tests.

**Comment by chris-doehring** [comment]
Hi @ftw-soft, thanks for your quick response. Indeed, there are no tests here at the moment, but that fact only should make clear that it's really important to add them. I'm using this package for a project and to be honest: I'm a bit worried about using it without it having any unit tests at all. Adding an automatic CI to prepare for these tests should be a sign that tests in this project are something to be added in future.

But there is also a second aspect: Although this package does not have a lot of dependencies, the build alone makes sure that they are compatible to the supported php versions, using composer. Composer would fail if it is not able to build this project for a php version.

**Comment by chris-doehring** [comment]
As mentioned in #5, I will try to work on an http client independend integration for the default behaviour, and for these changed classes, I will write unit tests.

**Comment by chris-doehring** [comment]
Thanks! :)

**Pull request merged**
